<?php

/**
 * JobeetTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object JobeetTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Jobeet');
  }
}
