<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2023/03/31 09:10:06
sfConfig::add(array(
  'sf_.actions' => NULL,
  'sf_use_database' => true,
  'sf_i18n' => false,
  'sf_compressed' => false,
  'sf_check_lock' => false,
  'sf_csrf_secret' => '66e206554e3db385657179b315c9dec97a20756b',
  'sf_escaping_strategy' => true,
  'sf_escaping_method' => 'ESC_SPECIALCHARS',
  'sf_no_script_name' => false,
  'sf_cache' => false,
  'sf_etag' => true,
  'sf_web_debug' => false,
  'sf_error_reporting' => 341,
  'sf_file_link_format' => NULL,
  'sf_admin_web_dir' => '/sf/sf_admin',
  'sf_web_debug_web_dir' => '/sf/sf_web_debug',
  'sf_standard_helpers' => array (
  0 => 'Partial',
  1 => 'Cache',
),
  'sf_enabled_modules' => array (
  0 => 'default',
),
  'sf_charset' => 'utf-8',
  'sf_logging_enabled' => false,
  'sf_default_culture' => 'en',
));
