<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2023/03/31 09:10:09

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=host.docker.internal:8002;dbname=jobeet',
  'username' => 'jobeet',
  'password' => 'jobeet',
  'name' => 'doctrine',
)),);
