<?php
// auto-generated by sfSecurityConfigHandler
// date: 2023/03/31 09:10:24
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    '.setting' => NULL,
    '.actions' => NULL,
  ),
  'security' => 
  array (
    'access_control' => 
    array (
      0 => 
      array (
        'path' => '^/backend',
        'roles' => 'IS_AUTHENTICATED_FULLY',
      ),
    ),
  ),
);
